/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IMyFeaturedContainerData } from './my-featured-container.data';
import { IMyFeaturedContainerProps } from './my-featured-container.props.autogenerated';

/**
 *
 * MyFeaturedContainer component
 * @extends {React.PureComponent<IMyFeaturedContainerProps<IMyFeaturedContainerData>>}
 */
export default class MyFeaturedContainer extends React.PureComponent<IMyFeaturedContainerProps<IMyFeaturedContainerData>> {
    public render(): JSX.Element {
        const { slots } = this.props;

        return (
            <div className='row'>
                <h1>Container</h1>
                <div className="row">
                    {slots.slot1[0]}
                    {slots.slot2[0]}
                </div>
            </div>
        );
    }
}
