/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ITextPageData } from './text-page.data';
import { ITextPageProps } from './text-page.props.autogenerated';

/**
 *
 * TextPage component
 * @extends {React.PureComponent<ITextPageProps<ITextPageData>>}
 */
export default class TextPage extends React.PureComponent<ITextPageProps<ITextPageData>> {
    public render(): JSX.Element {
        const { config, resources } = this.props;

        return (
            <div className='row'>
                <h2>Config Value: {config.showText}</h2>
                <h2>Resource Value: {resources.resourceKey}</h2>
            </div>
        );
    }
}
