/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IDataActionExampleData } from './data-action-example.data';
import { IDataActionExampleProps } from './data-action-example.props.autogenerated';

/**
 *
 * DataActionExample component
 * @extends {React.PureComponent<IDataActionExampleProps<IDataActionExampleData>>}
 */
export default class DataActionExample extends React.PureComponent<IDataActionExampleProps<IDataActionExampleData>> {
    public render(): JSX.Element {
        const { config, resources } = this.props;
        console.log(this.props);
        return (
            <div className='row'>
                <h2>Config Value: {config.showText}</h2>
                <h2>Resource Value: {resources.resourceKey}</h2>
            </div>
        );
    }
}
