/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IMyFeaturedContentData } from './my-featured-content.data';
import { IMyFeaturedContentProps } from './my-featured-content.props.autogenerated';

/**
 *
 * MyFeaturedContent component
 * @extends {React.PureComponent<IMyFeaturedContentProps<IMyFeaturedContentData>>}
 */
export default class MyFeaturedContent extends React.PureComponent<IMyFeaturedContentProps<IMyFeaturedContentData>> {
    public render(): JSX.Element {
        const {
            config: {
                imageAlignment, imageSrc
            }
        } = this.props;
        return (
            <div className='row'>
                <img src={imageSrc} alt='image' style={{ float : imageAlignment }} />
            </div>
        );
    }
}
