/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import TextPage from '../text-page';
import { ITextPageData } from '../text-page.data';
import {
  ITextPageConfig,
  ITextPageProps
} from '../text-page.props.autogenerated';

const mockData: ITextPageData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ITextPageConfig = {
  showText: 'text-page'
};

const mockActions = {};

describe('TextPage', () => {
  let moduleProps: ITextPageProps<ITextPageData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ITextPageProps<ITextPageData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <TextPage {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
