export const mockResources = {
    findInStoreLinkText: 'Find in store',
    findInStoreHeaderText: 'Buy now, pick up in a store',
    findInStoreDescriptionText: 'Search for product availability at stores within 50 miles of you.',
    priceFree: 'Free',
    originalPriceText: 'Was:',
    currentPriceText: 'Now:',
    addToCartText: 'Add to cart',
    outOfStockText: 'Out of Stock',
    averageRatingAriaLabel: 'Average {0} of {1} stars',
    selectDimensionFormatString: 'Choose a {0}',
    productDimensionTypeColor: 'Color',
    productDimensionTypeConfiguration: 'Configuration',
    productDimensionTypeSize: 'Size',
    productDimensionTypeStyle: 'Style',
    addToWishlistButtonText: 'Add to Wishlist',
    removeFromWishlistButtonText: 'Remove from Wishlist',
    addToWishlistMessage:'Added to your wishlist',
    removedFromWishlistMessage:'Removed from your wishlist',
    addItemToWishlistError:'Unable to add item to wishlist',
    removeItemFromWishlistError:'Unable to remove item from wishlist',
    nameOfWishlist: 'My Wishlist',
    inputQuantityAriaLabel: 'Quantity To Purchase',
    productQuantityHeading: 'Quantity',
    errorMessageOutOfStock: 'This product is out of stock',
    errorMessageOutOfRangeOneLeft: 'There is only one product left. Please choose quantity within the available range',
    errorMessageOutOfRangeFormat: 'There are only {numLeft} products left. Please choose quantity within the available range',
    productDimensionTypeColorErrorMessage: 'Color is required. Please choose a color',
    productDimensionTypeConfigurationErrorMessage: 'Configuration is required. Please choose a configuration',
    productDimensionTypeSizeErrorMessage: 'Size is required. Please choose a size',
    productDimensionTypeStyleErrorMessage: 'Style is required. Please choose a style',
    buyboxErrorMessageHeader: 'There are some issues',
    addedToCartFailureMessage: 'Add to cart failed. Please refresh and retry',
    maxQuantityLimitText: 'You can only add {quantity} of this item to your shopping bag'
};